### ISSUE TITLE
Files are not deleted

### ISSUE THREAD

**Issue by Longjogger** [nextcloud/files_retention#101]
Hi everybody,

I wanna use the retention app. The configuration is correct, but files are not deleted.

### Steps to reproduce
1. Uploaded files get automatically a tag through the workflow app
2. 24 hours before the planned deletion I get a notification, that the file will be deleted in 24 hours
3. But file will be not deleted

### Server configuration
Operating system: Ubuntu 18.01
Web server: Apache 2.4
Database: MariaDB 10.1
PHP version: 7,2
Nextcloud version: 18.0.10

Where did you install Nextcloud from:
official website

Best regards!

**Comment by sualko** [comment]
Does this issue still persist? Which cron type are you using?
