### ISSUE TITLE
Old files are not deleted

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files_retention#102]
have old files, e.g. 20 days old, assign tag so they should get deleted.
See that all new files are getting deleted, but not the 20 days old one.

It seems that retention matches only files that have a specific tag and are exactly x days old, but not ">= x days".

**Comment by sualko** [comment]
Do you still have this issue? Because if I look at the code, it seams also older files should be deleted:

https://github.com/nextcloud/files_retention/blob/30053c4a387fa82861233b43f29d3d12823b8f84/lib/BackgroundJob/RetentionJob.php#L216

**Comment by sualko** [comment]
If you still have this issue, please reopen.
