### ISSUE TITLE
Nextcloud 20 support

### ISSUE THREAD

**Issue by duritong** [nextcloud/files_retention#103]
App does not yet support nextcloud 20. Thank you for making it compatible.

**Comment by jacotec** [comment]
I'm pretty worried as this app is from Netxcloud itself ... not compatible after 2 months?

**Comment by jupsoleil** [comment]
Is this being obsoleted or replaced?

**Comment by mtkraai** [comment]
This is a hard requirement for our new deployment.  I've been forcing the app install for testing, and it seems to work fine.

There's a branch for it, and it's in the documentation, but no release.  Perhaps it was overlooked?

**Comment by duritong** [comment]
@rullzer ping since you mostly pushed the last releases.

**Comment by menace133780** [comment]
we would also appreciate the fuctionality on NC v20!

**Comment by duritong** [comment]
There seems to be a branch and everything setup, just no release?

CC @rullzer @nickvergessen @MorrisJobke @eppfel @LukasReschke

**Comment by nolens** [comment]
Hello, 
@rullzer @nickvergessen @MorrisJobke @eppfel @LukasReschke

Any roadmap here?

Best
Thomas

**Comment by nickvergessen** [comment]
Please stop mentioning me, thanks

**Comment by tflidd** [comment]
> Please stop mentioning me, thanks.
> I'm not responsible for this app and neither have the release key.

You have the second most contributions here and nobody from Nextcloud was responding. Is there a different communication channel that people can use to reach out? Who is actually responsible?

**Comment by duritong** [comment]
Thank you! @rullzer
