### ISSUE TITLE
Fix position of clock in trashbin icon

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/files_retention#11]
By @Bugsbane:

@eppfel - The clock on the garbage can looks like it's placement a little high. Could we get it aligned so that the space above it is equal to the space below (and the spaces on the sides)?

Ref https://github.com/nextcloud/server/issues/856#issuecomment-247257413

**Comment by eppfel** [comment]
This is intentional, as it is more the gravitational center. If you place it closer to the bottom, the distance to the sides gets to narrow. But feel free to play around with it. Maybe it should be a little lower.
