### ISSUE TITLE
Retention of files does not show current configuration settings

### ISSUE THREAD

**Issue by neeral85** [nextcloud/files_retention#120]
Nextcloud 15.0.2

### Steps to reproduce
1. configure Retention of files for a specific tag and apply
2. configuration does note appear, but tag can't be selected anymore

### Expected behaviour
already configured Retention settings should be visible & it should be possible to delete them

### Actual behaviour
already configured Retention settings are not visible

### Server configuration

**Operating system**:Ubunut 18

**Web server:** Apache

**Where did you install Nextcloud from:**
https://www.techandme.se/nextcloud-vm/

**Comment by v-bulynkin** [comment]
The same on Debian 10, Apache, Nextcloud 21.0.2, Retention 1.10.1.

**Comment by AmberDante** [comment]
Hi,

Possible solution #118 by @japerrin https://github.com/nextcloud/files_retention/issues/118#issuecomment-833494938

You should delete retention rules from `oc_retention` table linked to deleted tags.

> DELETE FROM oc_retention WHERE tag_id not in (SELECT id FROM oc_systemtag);

It’s work in MySQL DB too.

**Comment by v-bulynkin** [comment]
Thanks for the information, but unfortunately it is not a solution.
Even after I trancate the whole table
```sql
truncate table oc_systemtag;
```
, create a new tag and configure it via Automated tagging and Retention, the tag is still hidden.

Nextcloud 23.0.0, PHP 8.0.13, Mysql 10.4.22, Retention 1.12.0

How the **oc_systemtag** table looks afterwards:
```
MariaDB [nextcloud]> SELECT * FROM oc_systemtag;
+----+---------------------+------------+----------+
| id | name                | visibility | editable |
+----+---------------------+------------+----------+
|  1 | outlook-del-14-days |          1 |        0 |
+----+---------------------+------------+----------+
1 row in set (0.000 sec)
```
