### ISSUE TITLE
Create new Version

### ISSUE THREAD

**Issue by Phylu** [nextcloud/files_retention#133]
Please provide a new version of the files_retention plugin that is compatible with Nextcloud 22.
@rullzer @nickvergessen 

### Steps to reproduce
1. Install File Retention on Nextcloud 22

### Expected behaviour
It should work

### Actual behaviour
It does not work, as its dependencies denote that Nextcloud <= 21 is needed.
![Screenshot 2021-07-07 at 12 06 13](https://user-images.githubusercontent.com/587332/124741269-cceb0f00-df1b-11eb-993b-92cf05f8d1db.png)

**Comment by nickvergessen** [comment]
It's already on the way and will come in the next couple of days.

**Comment by Phylu** [comment]
> It's already on the way and will come in the next couple of days.

Thanks a lot! :)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/files_retention/releases/tag/v1.11.0
