### ISSUE TITLE
Systemtag deleted - retention_job stays?

### ISSUE THREAD

**Issue by sackla** [nextcloud/files_retention#15]
Hi there.
Not sure if this is the right place to post this. Please point me to the right one if I am wrong here!

I've got this error reoccurring daily in the nextcloud logs:
`{"reqId":"K6QHnoCjHwiyXJ1QBC59","remoteAddr":"213.47.76.124","app":"core","message":"Error while running background job (class: OCA\\Files_Retention\\BackgroundJob\\RetentionJob, arguments: Array\n(\n    [tag] => 5\n)\n): {\"Exception\":\"OCP\\\\SystemTag\\\\TagNotFoundException\",\"Message\":\"Tag id(s) not found\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_retention\\\/lib\\\/BackgroundJob\\\/RetentionJob.php(93): OC\\\\SystemTag\\\\SystemTagManager->getTagsByIds(5)\\n
#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\Files_Retention\\\\BackgroundJob\\\\RetentionJob->run(Array)\\n
#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n
#3 \\\/var\\\/www\\\/nextcloud\\\/cron.php(143): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n
#4 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/SystemTag\\\/SystemTagManager.php\",\"Line\":120}","level":3,"time":"2017-01-01T12:24:09+00:00","method":"GET","url":"\/cron.php","user":"--"}`

As the trace says: The backgroundjob "RetentionJob" is called with a tagid which was deleted. Obviously I deleted the systemtag before deleting the retention-rule. 
I see no way to delete the backgroundjob on the admin-interface. Is deleting the line from "oc_jobs" in the database the way to "quickfix" this?

**Comment by nickvergessen** [comment]
Yeah, but basically deleting the retention rule should also delete the job
