### ISSUE TITLE
Navigate to Settings > Administration > Workflow shows errors in Log

### ISSUE THREAD

**Issue by BobSilent** [nextcloud/files_retention#155]
When navigating to `Settings > Administration > Workflow` 
the following errors are logged:

```
[jsresourceloader] Error: Could not find resource core/js/systemtags/systemtagscollection.js to load

GET /settings/admin/workflow
[jsresourceloader] Error: Could not find resource core/js/systemtags/systemtagmodel.js to load

GET /settings/admin/workflow
[jsresourceloader] Error: Could not find resource core/js/systemtags/systemtags.js to load

GET /settings/admin/workflow
[jsresourceloader] Error: Could not find resource core/js/oc-backbone-webdav.js to load

GET /settings/admin/workflow
```

https://github.com/nextcloud/files_retention/blob/ef46fcee0a05125ee49fec129c0cd966600fef0d/templates/admin.php#L23-L26

**Comment by nickvergessen** [comment]
Which version? Works fine here with master and stable23 on the matching versions.

**Comment by BobSilent** [comment]
nextcloud
<img src="https://user-images.githubusercontent.com/13506173/163039563-51745015-612e-4d99-a1db-79669e850584.png" width="300px"/>
it is a docker deployment with `image: nextcloud:23.0.1-fpm-alpine`

Files Retention
<img src="https://user-images.githubusercontent.com/13506173/163039485-ea8d9279-de3d-4f5b-99c8-ac95baaa7bd7.png" width="400px"/>

do you have the missing... my missing files in `core/js` folder?
my folder looks like this
<img src="https://user-images.githubusercontent.com/13506173/163040157-a44b1f55-42f1-4fd3-a7be-e32da0635b88.png" width="200px"/>
and the content is similar to the content here: https://github.com/nextcloud/server/tree/master/core/js
only an additional `dist` folder exists, which does not contain the files:
<img src="https://user-images.githubusercontent.com/13506173/163040330-84ece3c6-8bb8-4793-9926-2d54077fea4d.png" width="200px"/>

**Comment by nickvergessen** [comment]
Please update to 23.0.3

**Comment by BobSilent** [comment]
no difference, still the errors in log
![image](https://user-images.githubusercontent.com/13506173/163047985-d9ba3790-c396-4abf-b5c7-cc12ad6843cd.png)

![image](https://user-images.githubusercontent.com/13506173/163048064-1fd230ae-12dc-47d1-b16d-36eb62ae5efb.png)

**Comment by nickvergessen** [comment]
Right, I had the files_automatedtagging app enabled so that's why it still worked...

**Comment by nickvergessen** [comment]
Fix in https://github.com/nextcloud/files_retention/pull/160
