### ISSUE TITLE
Exception when trying to set up retention

### ISSUE THREAD

**Issue by mattti** [nextcloud/files_retention#172]
When I try to setup a new retention rule, it seems to work.
The UI shows the rule, however it is impossible to delete it and when refreshing the UI, the rule is gone.
I checked the DB, the retention table is empty.

Eventually I managed to catch an exception in the log:

`
 {"Exception":"Exception","Message":"OCA\\Files_Retention\\Controller\\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/custom_apps/files_retention/lib/Controller/APIController.php' line 82","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Retention\\Controller\\APIController"},"addRetention"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Retention\\Controller\\APIController","addRetention",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files_retention.API.addRetention"}]},{"file":"/var/www/html/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files_retention/api/v1/retentions"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OCA\\Files_Retention\\Controller\\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"addRetention","class":"OCA\\Files_Retention\\Controller\\APIController","type":"->","args":[3,0,10,0]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Retention\\Controller\\APIController"},"addRetention"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Retention\\Controller\\APIController"},"addRetention"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Retention\\Controller\\APIController","addRetention",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files_retention.API.addRetention"}]},{"file":"/var/www/html/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files_retention/api/v1/retentions"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/files_retention/lib/Controller/APIController.php","Line":82},"CustomMessage":"--"}}
`

Retention version: 1.13.1
Nextcloud Version: 24.0.0

**Comment by jjjolley** [comment]
I'm having the same problem:

Exception: Argument 1 passed to OCA\Files_Retention\Controller\APIController::addRetention() must be of the type string, int given, called in /var/www/vhosts/WEBSITE/httpdocs/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/vhosts/WEBSITE/httpdocs/apps/files_retention/lib/Controller/APIController.php' line 82

**Comment by serial8killer** [comment]
I'm having the same problem

Nextcloud version: 24.0.0
Retention version: 1.13.1

Exception: Argument 1 passed to OCA\Files_Retention\Controller\APIController::addRetention() must be of the type string, int given, called in /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/config/www/nextcloud/apps/files_retention/lib/Controller/APIController.php' line 82/config/www/nextcloud/lib/private/AppFramework/App.php - line 172:OC\AppFramework\Http\Dispatcher->dispatch()/config/www/nextcloud/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main()/config/www/nextcloud/lib/base.php - line 1023:OC\Route\Router->match()/config/www/nextcloud/index.php - line 36:OC::handleRequest()Caused by TypeError: Argument 1 passed to OCA\Files_Retention\Controller\APIController::addRetention() must be of the type string, int given, called in /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:OCA\Files_Retention\Controller\APIController->addRetention()/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:OC\AppFramework\Http\Dispatcher->executeController()/config/www/nextcloud/lib/private/AppFramework/App.php - line 172:OC\AppFramework\Http\Dispatcher->dispatch()/config/www/nextcloud/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main()/config/www/nextcloud/lib/base.php - line 1023:OC\Route\Router->match()/config/www/nextcloud/index.php - line 36:OC::handleRequest()

**Comment by dakeeper** [comment]
Hello,

same problem here.

Nextcloud Version 24.0.0
Retention Version  1.13.1

Exception: OCA\Files_Retention\Controller\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/vhosts/****.de/nc.****.de/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/vhosts/****.de/nc.****.de/apps/files_retention/lib/Controller/APIController.php' line 82


[index] Fehler: Exception: OCA\Files_Retention\Controller\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/vhosts/huthkg.de/nc.huthkg.de/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/vhosts/huthkg.de/nc.huthkg.de/apps/files_retention/lib/Controller/APIController.php' line 82 at <<closure>>

0. /var/www/vhosts/****.de/nc.*****.de/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/vhosts/*****.de/nc.****.de/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/vhosts/****.de/nc.****.de/lib/base.php line 1023
   OC\Route\Router->match()
3. /var/www/vhosts/****.de/nc.****.de/index.php line 36
   OC::handleRequest()

POST /index.php/apps/files_retention/api/v1/retentions
from 109.**.**.** by ***** at  #2022-05-18T09:05:52+00:00

Verursacht durch TypeError: OCA\Files_Retention\Controller\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/vhosts/****.de/nc.****.de/lib/private/AppFramework/Http/Dispatcher.php on line 225

0. /var/www/vhosts/****.de/nc.*****.de/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Files_Retention\Controller\APIController->addRetention()

1. /var/www/vhosts/*****.de/nc.*****.de/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController()

2. /var/www/vhosts/*****.de/nc.*****.de/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

3. /var/www/vhosts/*****.de/nc.*****.de/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

4. /var/www/vhosts/*****.de/nc.*****.de/lib/base.php - line 1023:

OC\Route\Router->match()

5. /var/www/vhosts/*****.de/nc.*****.de/index.php - line 36:

OC::handleRequest()

**Comment by mstsidp** [comment]
Same problem.

Nextcloud 24.0.1
Retention 1.13.1

[index] Error: Exception: OCA\Files_Retention\Controller\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/files_retention/lib/Controller/APIController.php' line 82 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1023
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

POST /apps/files_retention/api/v1/retentions
from 10.5.12.254 by admin at 2022-05-24T10:40:49+02:00

**Comment by ChR-iSz** [comment]
Same here. Hello Developer... Can you fix that ?

**Comment by ChR-iSz** [comment]
Okay, fixed itself: Looks like a typo...

Edit follow file:  `nano /var/www/html/nextcloud/apps/files_retention/lib/Controller/APIController.php`

Change tagid datatype from string to int (see screenshot).
<img width="914" alt="Bildschirmfoto 2022-05-25 um 12 30 14" src="https://user-images.githubusercontent.com/49807897/170242404-38ecfb9d-e5af-47f0-9a11-5e977c52e095.png">
 to int:

**Comment by jjjolley** [comment]
@ChR-iSz  Thanks this worked but now we have one other problem. The Parent file is also tagged with child.

Meaning, after setting up a Flow: 
File System Flow - is tagged with - (retention-delete-31-days)
Automated tagging Automated tagging of files (auto-delete-31-days)

The parent folder will be tagged with both (retention-delete-31-days) and (auto-delete-31-days)

So now my parent folder will be deleted too when all I want is the children to be deleted.

**Comment by tohn** [comment]
I'm very interested in getting this fixed since I don't have access to the nextcloud files itself (shared nextcloud).

@jjjolley isn't it possible to delete the tag on the parent as a workaround?

@ChR-iSz thank you, now there is even a PR (#174) :)
