### ISSUE TITLE
l10n still wonky in emails and notifications

### ISSUE THREAD

**Issue by asaage** [nextcloud/files_retention#190]
Followup #173
___
notification in app:
![image](https://user-images.githubusercontent.com/4138336/179215623-69407728-7cd6-4fdd-90c1-c62e20e1b089.png)
___
notification-E-mail:
![image](https://user-images.githubusercontent.com/4138336/179215964-b595e336-233c-42df-9a7e-092dc53edef2.png)

This should be the right languange throughout not a mix of two languages.

**Comment by nickvergessen** [comment]
Can you try https://github.com/nextcloud/files_retention/pull/191 ?

**Comment by asaage** [comment]
I already pointed out that the translation is theoretically covered.

>  the $languageCode parameter is put into the wrong place

What does that mean? Should i put that somewehere else than config/config.php?

**Comment by nickvergessen** [comment]
It a bug in the apps code:
https://github.com/nextcloud/files_retention/pull/191/files

It tries to load the language file `*` of the app `de_DE` instead of the file `de_DE` of the app `files_retention`

**Comment by nickvergessen** [comment]
If you can not apply the patch, no worries. I can merge it next week and then look into another release

**Comment by asaage** [comment]
quickly added that change with vim..
👍🏼 looks good - e-mail should be solved then as well.

![image](https://user-images.githubusercontent.com/4138336/179229818-a6663b1f-0897-4e5a-a16d-4d6734b0d344.png)
