### ISSUE TITLE
No user documentation

### ISSUE THREAD

**Issue by ArchPrime** [nextcloud/files_retention#20]
Hi - I cannot seem to find anywhere instructions or help files for use with this app.  Installing the ap seems not to change the behaviour of NextCloud 11 (or Owncloud 9.13) in any noticeable way.  Where should I look for help?

**Comment by KB7777** [comment]
@ArchPrime 
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/file_versioning.html

**Comment by ArchPrime** [comment]
Thanks for your reply.
Does this general helpfile specifically relate to the files_retation app?

Perhaps I am trying to do the wrong thing here, but this app was suggested to me as a way to clean up a series of copies of same filename  sent to nextcloud as a daily backup – the idea being maybe a week’s worth of backups are kept, with the oldest being auto deleted to make space for incoming newer versions.

Am I on the right track in trying to use this app in this way?

Thanks
Paul

**Comment by KB7777** [comment]
Well, I'm sorry. I was wrong above :) 

This is the app:

![workflow](https://cloud.githubusercontent.com/assets/23165598/22732276/e459b67e-eded-11e6-88d6-1dabdccf8228.png)

**Comment by ArchPrime** [comment]
Perhaps something still wrong – I can’t see a way to access that menu

Clicking on ‘Apps’ just gives me a blank page now (although I previously was at least able to install the app from Nextcloud appstore from there )

Files_retention is the first and only 3rd party app I have tried – wondering if it may have caused the blank apps page issue?

What url should I see when accessing that app menu?
[cid:image001.jpg@01D28266.DDECBB80]

Cheers
Paul

**Comment by KB7777** [comment]
settings/admin/workflow

**Comment by ArchPrime** [comment]
Ah, ok found it.

Not sure how to use though – the number of days can’t be permanently changed, and  the ‘Create’ button is greyed out, and I see no obvious way to distinguish which files are retained vs not retained, and where?

[cid:image001.jpg@01D2826F.6F07AB40]
Where would I find instructions that would allow me to automatically have my files which are ftp-ed into a certain folder (only) subject to auto deletion after n days?

**Comment by KB7777** [comment]
I don't use this app, so sorry, but I don't know :)

**Comment by ArchPrime** [comment]
Thanks anyway for your help

Cheers
Paul

**Comment by werkelchen** [comment]
I had similar problems. There is a proper description or manual missing for the file-retention-app. And the screenshot is misleading. You think, the options of the app will be displayed in the side-infobox of files/folders. Instead, they are visible and modifiable in the general preference-section. You think, you will give a file/folder a date, period or something like that, and it's done. Right, but wrong way.

The way things work: you have to assign a tag to a file/folder. Than you can go to the administration-site of your nextcloud-installation, click the "workflow"-tab on the left side, go to the end of the following site. Than you can see the detail of the app-screenshot. Chose the given tag and your period and your done. Sounds like a long way round, but you get used to it.
Hopefully they will retouch the description an the manual and get it easier to understand. 

You have to install & activate three apps in order, to get the file retention working:
- file access control
- automatic tagging
- file retention

**Comment by nickvergessen** [comment]
Documentation has been written:
https://docs.nextcloud.com/server/12/go.php?to=admin-files-retention

Sorry for the delay
