### ISSUE TITLE
file link broken in notification when user has opened the Dashboard

### ISSUE THREAD

**Issue by rriemann** [nextcloud/files_retention#210]
### Steps to reproduce
1. create a tag X
2. create a retention rule for tag X and enable notifications a day ahead
3. add tag X to a file and wait until a notification is sent
4. navigate to the dashboard
5. click on the filename in the notification
6. see how the dashboard is reloaded (entire page reload)

### Expected behaviour

I can remove the tag or cancel file deletion otherwise from the notification.

Ideas for implementation:

a) have a button in the notification "remove retention tag"
b) have a quick way to find the file in the file app, so that the tag can be removed from the file settings side bar

### Actual behaviour

I click on the notification and the link of the file brings me to the dashboard (that was already open)

### Server configuration

**Nextcloud version:** 24.0.6 Enterprise

**version of the retention plugin:** 	1.13.2

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Comment by nickvergessen** [comment]
Patch at https://github.com/nextcloud/files_retention/pull/238
