### ISSUE TITLE
🖌️ Design review 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/files_retention#222]
## Based on

* #196 

## Overall

* [x] Adjust heading to "File retention & automatic deletion"
* [x] Table content is a bit indented / has left padding, not left-aligned with the rest – left and right outer padding can probably be removed
* [x] Time input field
  * [x] input text should be right-aligned too, like when it’s saved
* [x] "Time" options look better lowercased so it’s "14 days" instead of "14 Days"
* [x] Combine "Retention" and "Time" into 1 column, "Retention time"
* [x] Remove "Active" column, error notification via notecard instead
* [x] "Notify users a day before retention will delete a file"→ "Notify owner a day before a file is automatically deleted"
* [x] Headings:
  * [x] Tag → "Files tagged with"
  * [x] After → "From date of"
  * [x] Actions → can be deleted
* [x] Right-align actions
* [x] Make + button secondary
  * [x] with text "Create"
* [ ] Screenshot in documentation needs updating https://github.com/nextcloud/documentation/pull/9224

## To report at nextcloud/vue

* [ ] Time input field https://github.com/nextcloud/nextcloud-vue/issues/3376
  * [ ] Is smaller than the others → text input component is smaller than the multiselect component
* [ ] Multiselect https://github.com/nextcloud/nextcloud-vue/issues/3377
  * [ ] When tabbing to a value but not confirming via enter, then coming back to it, wrong value is preselected
  * [ ] Text input vs actual value shifts by 1 px
  * [ ] Rounded corners for dropdown
* [ ] SettingsSections https://github.com/nextcloud/nextcloud-vue/issues/3378
  * [ ] General settings: Would be nice to have some space on bottom of page always, like 30vh (30% of viewport height)

**Comment by jancborchardt** [comment]
Wow @nickvergessen, speedy turnaround time! :) Nice work
