### ISSUE TITLE
Does this work with nextcloud 11.0.2

### ISSUE THREAD

**Issue by ddanielww** [nextcloud/files_retention#25]
Installed this app on nextcloud 11.0.2 and created a test tag called Delete - 1 day and assigned this in the workflow tab and set it to 1 day. 
I've then added this tag to a file but the file has not been deleted ?

Any ideas welcome as I want to use this app.

**Comment by nickvergessen** [comment]
Is your cron job running?

**Comment by wiswedel** [comment]
NC 11 is no longer supported and this issue hasn't been updated in a very long time. I suggest to close it @nickvergessen
