### ISSUE TITLE
Retention job is not removed from jobList when admin deletes job.

### ISSUE THREAD

**Issue by jkimalane** [nextcloud/files_retention#26]
### Steps to reproduce
1. Add new retention job 
2. Inspect table oc_jobs and verify that new job has been added.
3. Delete previously created retention job
4. Inspect table oc_jobs and verify that previously created job still exists.

### Expected behaviour
Retention job should have been removed from oc_jobs table.

### Actual behaviour
Retention job is left behind in oc_jobs table although job's definition is removed from oc_retention table.

**Comment by rullzer** [comment]
Fixed
