### ISSUE TITLE
Retention breaks dropdown on workflow-admin-page

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/files_retention#30]
Dropdown with `files_retention`:

<img width="895" alt="bildschirmfoto 2017-04-29 um 12 05 47" src="https://cloud.githubusercontent.com/assets/19711361/25554708/7fc420ca-2cd4-11e7-9040-6175685707e1.png">

Dropdown without `files_retention`✅:
 
<img width="532" alt="bildschirmfoto 2017-04-29 um 12 06 27" src="https://cloud.githubusercontent.com/assets/19711361/25554704/67546982-2cd4-11e7-958f-7f70fe09b9ae.png">

@nextcloud/designers

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
retention is @rullzer

**Comment by rullzer** [comment]
I bet we load some stuff twice or something. I'll look into this.
