### ISSUE TITLE
Auto tagged files are not deleting in Group folders

### ISSUE THREAD

**Issue by AmmoInt** [nextcloud/files_retention#38]
### Steps to reproduce
1. auto tag files of size greater than 1KB
2. auto delete these tagged files after one day
3. Files are not auto deleted

### Expected behaviour
1. Deletion of auto tagged files works on test server with No LDAP authentication and not using shared folders.
2. Production server configured with shared folders only and LDAP authentication - deletion of auto tagged files does not work. Files are auto tagged but are not deleted after one day.

### Actual behaviour
auto tagged files are not deleted.

### General server configuration

**Operating system:** Linux nextcloud 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.2.9

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - redis
 - mysqlnd
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - smbclient
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:**  Nextcloud OVA from https://www.techandme.se/nextcloud-vm/

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_automatedtagging: 1.2.2
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - firstrunwizard: 2.1
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - previewgenerator: 1.0.7
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - files_external
 - files_videoplayer
 - gallery
 - survey_client
 - user_external
 - user_saml
```
</details>

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

"system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud",
            "nextcloud",
            "nextcloud.domain.com",
            
        ],
        "overwritehost": "nextcloud.domain.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "datadirectory": "\/var\/ncdata",
        "overwrite.cli.url": "http:\/\/nextcloud\/",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud_db",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "oc989awy4zxd",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/ncdata\/nextcloud.log",
        "logtimezone": "Europe\/London",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "hidden",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "nextcloud.domain.com",
        "mail_smtphost": "relay.nextcloud.domain.com",
        "mail_smtpport": "25",
        "skeletondirectory": "\/usr\/ieskeleton"

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Chrome
MS Edge
MS IE

**Operating system:**
Windows 10, 7

### Logs

Can provide if required though I have found this error:
Undefined offset: 0 at /var/www/nextcloud/apps/files_retention/lib/BackgroundJob/RetentionJob.php#162

#### Nextcloud log 
```
Insert your Nextcloud log here
```

#### Browser log
```

**Comment by gabasync** [comment]
I am having the same issue. Also files that are in the Group folders.

This is my duplicate post from the Nexclould forum support.

Nextcloud version 12.0.2
Operating system and version Ubuntu 16.04.2 (Nextcloud VM Image)
Apache or nginx version Apache 2.4.18
PHP version 7.0
Is this the first time you’ve seen this error?: Yes

Can you reliably replicate it? Yes

The issue you are facing: Workflow File Auto-tag / Auto-Deletion not deleting/working correctly
I have setup Workflow Collaborative Tag called “Retain for 14 Days”. To tag the Upload File I created A AutoTag
by saying If File Sioze upload is greater/equal to 0MB apply the “Retain for 14 Days”. I then added a File Retention
rule to delete a file after 14 days with the tag " “Retain for 14 Days”. My problem started I believe when I decreased
my Version and Trash auto clean times (see my below changes/additions). I noticed all my files do have the
"Retain for 14 Days" tag after uploading but are being kept over 14 days (several over a month).

The output of your Nextcloud log in Admin > Logging: Did not see what to paste here
The output of your Apache/nginx/system log in /var/log/____: Did not see what to paste here

The output of your config.php file in /path/to/nextcloud:
File: /var/www/nextcloud/config/config.php
My Changes/Additions:
‘trashbin_retention_obligation’ => ‘1, 2’,
‘versions_retention_obligation’ => ‘1, 2’,

File: /etc/php/7.0/apache2/php.ini
My Changes/Additions:
output_buffering = 0
max_execution_time = 7200
max_input_time = 7200
post_max_size = 5100M
upload_max_filesize = 5000M

My error from nextcloud.log each night is:

{"reqId":XXXXX","level":3,"time":"2017-10-25T04:30:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined offset: 0 at \/var\/www\/nextcloud\/apps\/files_retention\/lib\/BackgroundJob\/RetentionJob.php#162","userAgent":"--","version":"12.0.2.0"}


![workflow_tags_autotag_retention](https://user-images.githubusercontent.com/32149439/32027556-b9489be4-b9b7-11e7-93d0-a70dcec67a10.JPG)

**Comment by nickvergessen** [comment]
Can you try the following modification: https://github.com/nextcloud/files_retention/pull/39/files

**Comment by gabasync** [comment]
Hello. I added the mod file. My apologies up silly question. To invoke the
script I tried manually running crontab . I researched the occ command. I
do not.for the life of me see how to just invoke/run the files_retention
app or individually the modded. Php file.

**Comment by AmmoInt** [comment]
Hi and thanks for responding so soon.
Forgive me but I am a relative newbie with Linux.
Should I create this PHP file , create a new directory called "BackgroundJob" in /var/www/nextcloud/lib and place the RetentionJob.php in there?
If so this is what I have done. Should we then see results the next time the cron job runs cron.php?
Many thanks.

**Comment by gabasync** [comment]
AmmoInt,

You will find the file under:
/var/www/nextcloud/apps/files_retention/lib/BackgroundJob
Its called RetentionJob.php
The ownerships are:
-rw-r--r-- 1 www-data www-data 5481 Oct 26 06:45 RetentionJob.php

You can use a editor like vi to add the edits or just retrieve the file and overwrite the original. I made a copy of the original with the shell command sudo cp -p RetentionJob.php RetentionJob.php.orig. The -p option keeps the ownerships as a backup.

I have posted basically the same question as you on the NextCloud forums under:
https://help.nextcloud.com/t/bug-fix-test-for-files-retention-how-to-invoke-a-modded-app-via-shell/22815

I tried the nextcloud command line occ and also running crontab but I did not invoke it correctly. I would think if you waited unless we get a answer, it will try on the next run. 

Hope this helps

**Comment by AmmoInt** [comment]
Many thanks for your help gabasync.
I added the php file to /var/www/nextcloud/apps/files_retention/lib/BackgroundJob and matched the permissions of the existing file (which was renamed) but it doesn't seem to have worked on existing files. In case it would only work on subsequently uploaded files I uploaded a new file yesterday which was tagged correctly but there are still a few hours to go until it has been uploaded for 24 hours so I will confirm on Monday of this file has been deleted.
Thanks to both for your help.

**Comment by gabasync** [comment]
To nickvergessen:
I checked after, what I believe was the midnight crontab run or whatever controls the files_retention job, and all the previous files tagged "Retain for 14 Days" have been deleted correctly. I also saw no error entry in the /var/ncdata/nextcloud.log file, or at least "grep retention nextcloud.log" showed only the previous error entries. I guess my log debug level is not set high enough to also log the successful entry. If you want I can change that if possible and report.

Ammolnt:
I am glad I could be of help.

**Comment by AmmoInt** [comment]
nickvergessen and gabasync
OK.
In case I messed up with the RetentionJob.php that I uploaded I downloaded the original and modified it and reuploaded it and made sure the owner is www-data with 644 perms. On checking the log "grep retention nextcloud.log" it look like the job runs at around 14.45 so I will check again in approx 5 hours.

Thanks again gabasybc, you have been a great help once again.

**Comment by nickvergessen** [comment]
In this case downloading the complete file is okay because there have not been any other changes.

Otherwise the correct way to test it would be either applying the patch with some tool (like diff), or manually modify the file. Removing red lines (ignoring the -) and adding green lines (ignoring the +). The line numbers can help you to find the right section in the file in case it exists multiple times.

**Comment by AmmoInt** [comment]
Thanks Nick, that is exactly what I did as of my previous post. I guess we will see at 14:45 - 15:00.
If it works I can go live with the server. Fingers crossed.

**Comment by AmmoInt** [comment]
Hi Nick,
I can confirm this is now working and tagged files are being auto deleted.
Many thanks for responding so quickly and fixing the problem.

@ Gabasync - thanks for helping out a newbie. I appreciate all of your help.

Ammo.
PS. I'm not sure of the process, should I now close this issue or would you close this as you have fixed it Nick?
