### ISSUE TITLE
Register background job for existing rules on enabling the app

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/files_retention#390]
It would be nice if background jobs for already existing rules could be created on enabling the app.

Not sure if this is more a feature request or a bug, but it is confusing if you see all your rules configured well, but the files are not deleted just because the background jobs are missing. I have to re-configure all my ~30 rules just to create the background job.

(Sometimes I disable and re-enable all apps for troubleshooting, if you need an explination for. ;) )

**Comment by dire-alpaca** [comment]
@Pilzinsel64 Thank you for making this post. I spent the last few hours reviewing this app to identify why the rules were not happening. I would say this is a bug as the UI will show the configured rules, but the BackgroundJob isn't configured. It might be confusing to the end user.

For me this occurred when moving to Nextcloud 28 and the slight delay of 1.17.0 update. I moved to NC 28.0.1, but didn't notice this app was left behind until later. Then after updating/enabling, hit this issue. After removing and recreating the rules, the BackgroundJobs showed when running `php occ background-job:list`.
