### ISSUE TITLE
Automatic deletion does not delete folders

### ISSUE THREAD

**Issue by kylespencer** [nextcloud/files_retention#395]
Nextcloud 27.1.3 + Files Automated Tagging 1.17.0 + Retention 1.16.0

Automatic deletion removes tagged files a day later than expected, but otherwise works. However, empty folders remain despite also being tagged.

This appears to be a bug. Is there a fix or workaround?

**Comment by nickvergessen** [comment]
the problem is when a file is deleted, the parent folder is being "modified". So if that is your retention rule you have to wait the same time again.

**Comment by kylespencer** [comment]
Thank you for the clear explanation. That makes sense. 

Is there a way to create a separate flow that tags and delete empty folders?

**Comment by kylespencer** [comment]
Thank you for the clear explanation. That makes sense. 

Regarding workarounds: Is there a way to create a new flow that tags and deletes empty folders?
