### ISSUE TITLE
files_retention background job strange code

### ISSUE THREAD

**Issue by hjohanns** [nextcloud/files_retention#49]
### Steps to reproduce
1. See issue https://github.com/nextcloud/files_retention/issues/25 
2. To be sure, debug the value of offset inside the background job loop

### Expected behaviour
All the files that meet the conditions should be removed

### Actual behaviour
Only a tiny portion of the files is removed

### Server configuration
**Database:** Mysql
**Nextcloud version:** (see Nextcloud admin page)
See this on NC 9 and NC 13 (same code).
**Problem analysis**
I have analysed file 
apps/files_retention/lib/BackgroundJob/RetentionJob.php
because it seems to me this cannot work.
The job is removing files in batches of 1000 by default. It progresses by starting with a 0 offset, then adding the number of objects deleted to offset at the end of a loop instance ($offset += $limit;). The problem is that in
https://docs.nextcloud.com/server/13/developer_manual/api/OCP/SystemTag/ISystemTagObjectMapper.html
The offset parameter is defined as 
$offset (string) The last object id you already received
So it is an id and not a number of elements to skip.
I changed the code by updating offset with
`$offset= array_values(array_slice($fileids, -1))[0];`
that is, set offset to the last value of the retrieved fileids.
With that, I see that the retention job is lasting for a long time (maybe too long but that's another story).
Please as I am new to the NC code, can someone check on this?
Thanks, hjohanns

**Comment by nickvergessen** [comment]
Can you try to replace:
https://github.com/nextcloud/server/blob/bb352fb667e87ea0829f1da5f9e85c34bdefe9fa/lib/private/SystemTag/SystemTagObjectMapper.php#L125
With:
```php
$query->andWhere($query->expr()->gt('objectid', $query->createNamedParameter($offset), IQueryBuilder::PARAM_INT));
```
