### ISSUE TITLE
Folders not deleted if not empty

### ISSUE THREAD

**Issue by axiomen** [nextcloud/files_retention#510]
### Steps to reproduce
1. Create a tag for folders and set retention to X days.
2. Add something to the tagged folders.
3. After X days, if the folder is not empty, it does not get removed.

### Expected behaviour
Folder should get removed regardless of its contents. Particularly important for File drop folders.

### Actual behaviour
Folder does not get removed.

### Server configuration

**Operating system**: Fedora 39

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 8.3

**Nextcloud version:** 28.0.4

**Where did you install Nextcloud from:** Linuxserver.io

**List of activated apps:**
  - activity: 2.20.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_automatedtagging: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_retention: 1.17.1
  - files_scripts: 4.0.3
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - flow_notifications: 1.8.0
  - groupfolders: 16.0.6
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.1
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0

**Nextcloud configuration:** (this is a test system, the configuration is minimal)

```
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED"
        ],
        "dbtype": "mysql",
        "version": "28.0.4.1",
        "overwrite.cli.url": "https:\/\/REMOVED",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "defaultapp": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "upgrade.disable-web": true,
        "maintenance": false
    }
}

```

### Client configuration
**Browser:** Not relevant

**Operating system:** Not relevant

#### Nextcloud log (data/owncloud.log)
No logs pertaining to the issue

#### Browser log
N/A

**Comment by nickvergessen** [comment]
Well the problem is other people would want exactly the opposite.

Also note: due to technical things a folder is being recognized as modified when adding or deleting a file inside of them, so they are not removed when a file inside got removed as they are not "untouched since X days" if the modified option is used

**Comment by nickvergessen** [comment]
> Because right now if I have a folder scheduled to be deleted 14 days after Creation date, and someone uploads a file anytime within those 14 days, the folder isn't deleted at all. At least that's the behavior I observed. Even if at some point the folder becomes empty, it won't be deleted.

It should be deleted 14 days after it become empty.
