### ISSUE TITLE
Created entries not displayed in web interface

### ISSUE THREAD

**Issue by moorsey** [nextcloud/files_retention#57]
### Steps to reproduce
1. Create new file retention rule

### Expected behaviour
Rule should show in the web interface

### Actual behaviour
Rule does not show in the web interface, but previously used tag is removed from the drop down menu and cannot be used again

### Server configuration

**Operating system**:
Ubuntu 18.04.1

**Web server:**
Apache2
**Database:**
MariaDB

**PHP version:**
7.2.10

**Nextcloud version:** (see Nextcloud admin page)
15

**Where did you install Nextcloud from:**
Manual download from website

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_automatedtagging: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_fulltextsearch: 1.2.3
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.3
  - fulltextsearch_elasticsearch: 1.2.2
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - sharerenamer: 2.3.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.200.100.5"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "overwrite.cli.url": "http:\/\/10.200.100.5\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.8.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "32"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "core": {
            "installedat": "1545996644.5324",
            "lastcron": "1546527207",
            "lastupdateResult": "[]",
            "lastupdatedat": "1546525556",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_default_permission_cancreate": "no",
            "shareapi_default_permission_candelete": "no",
            "shareapi_default_permission_canshare": "no",
            "shareapi_default_permission_canupdate": "no",
            "shareapi_default_permissions": "1",
            "shareapi_enable_link_password_by_default": "yes",
            "shareapi_enforce_expire_date": "yes",
            "shareapi_enforce_links_password": "yes",
            "shareapi_expire_after_n_days": "30",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_fulltextsearch": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.7.0",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "logging"
        },
        "fulltextsearch": {
            "app_navigation": "0",
            "cron_err_reset": "1546011776",
            "enabled": "yes",
            "installed_version": "1.2.3",
            "provider_indexed": "{\"files\":\"1\"}",
            "search_platform": "OCA\\FullTextSearch_ElasticSearch\\Platform\\ElasticSearchPlatform",
            "types": ""
        },
        "fulltextsearch_elasticsearch": {
            "analyzer_tokenizer": "standard",
            "elastic_host": "http:\/\/localhost:9200",
            "elastic_index": "nextcloud",
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.2.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.5.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "sharerenamer": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "theming": {
            "cachebuster": "5",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "logoMime": "image\/png",
            "name": "",
            "slogan": "",
            "types": "logging",
            "url": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        }
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Chrome 71
IE11

**Operating system:**
Windows 10 Ent

#### Nextcloud log (data/owncloud.log)
```
Not found
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by moorsey** [comment]
Also logged here, but thought it may need to be here instead/also

nextcloud/server#13057

**Comment by nickvergessen** [comment]
> TypeError: Handlebars.compile is not a function[Weitere Informationen] retentionview.js:51:22
template
https://nextcloud16.local/appsshipped/files_retention/js/retentionview.js:51:22
render/<
https://nextcloud16.local/appsshipped/files_retention/js/retentionview.js:75:16
m.forEach
https://nextcloud16.local/core/vendor/underscore/underscore-min.js:5:2350
addMethod/<
https://nextcloud16.local/core/vendor/backbone/backbone.js:87:25
render
https://nextcloud16.local/appsshipped/files_retention/js/retentionview.js:68:4
_onClickSubmit
https://nextcloud16.local/appsshipped/files_retention/js/admin.js:108:4
_onClickSubmit self-hosted:975:17 dispatch
jquery.js:4434:14
add/r.handle
jquery.js:4121:5


@rullzer Handlebar change missing or failed?

**Comment by gixxxerg** [comment]
bump!   any news on this?

**Comment by Madic-** [comment]
Can confirm the bug with multiple nextcloud installations

**Comment by amarttinez** [comment]
Still having the same problem here. Didn't find any solution. Any news or workaround?

**Comment by wiswedel** [comment]
@rullzer

**Comment by amarttinez** [comment]
Hi @rullzer, do you know if there's any fix for this? Thanks!

**Comment by amarttinez** [comment]
> 
> 
> > TypeError: Handlebars.compile is not a function[Weitere Informationen] retentionview.js:51:22
> > template
> > https://nextcloud16.local/appsshipped/files_retention/js/retentionview.js:51:22
> > render/<
> > https://nextcloud16.local/appsshipped/files_retention/js/retentionview.js:75:16
> > m.forEach
> > https://nextcloud16.local/core/vendor/underscore/underscore-min.js:5:2350
> > addMethod/<
> > https://nextcloud16.local/core/vendor/backbone/backbone.js:87:25
> > render
> > https://nextcloud16.local/appsshipped/files_retention/js/retentionview.js:68:4
> > _onClickSubmit
> > https://nextcloud16.local/appsshipped/files_retention/js/admin.js:108:4
> > _onClickSubmit self-hosted:975:17 dispatch
> > jquery.js:4434:14
> > add/r.handle
> > jquery.js:4121:5
> 
> @rullzer Handlebar change missing or failed?

Still facing the issue. Have tried new installations with same result. @nickvergessen do you have any news? Can we do something to help on this? Thanks!

**Comment by rullzer** [comment]
Let me give this app some love soonish.

**Comment by gixxxerg** [comment]
updated version 1.4.1 results in same issue still

**Comment by rullzer** [comment]
Can you clear you cache?

Also any errors in your browser log etc?

**Comment by AND51** [comment]
Hi rullzer,

for me the new version 1.4.1 works. Thank you! I do not fully understand this bug: Do the invisible tags mean that they were just not visible in the browser or did they not work at all? In the MySQL database, I was able to find them. So it seems to me as if they were just invisible.

P.S.:

1. I updated to 1.4.1
2. I have NC 15.0.4 on Ubuntu 16.04 with Apache 2.4 and PHP-FPM 7.0
3. I cleared the browser cache and cookies
4. I flushed Redis cache
5. I restarted the webserver: systemctl restart apache* php*
6. Tags are now visible again.

Hope this helps.

**Comment by nickvergessen** [comment]
Invisible tags are not visible for normal users, admin users can still see and (un)assign them.

**Comment by amarttinez** [comment]
Updated to 1.4.1 and verified that now it works. File retention tags are now visible and can be managed. Thanks @rullzer and @nickvergessen for your quick response.

**Comment by manfredheitlager** [comment]
> Can you clear you cache?
> 
> Also any errors in your browser log etc?

Cleared cache in Chromed and Firefox.  No Browser errors logged either.
I have 2 similar instances running on different servers and on different domains.
Both have the same issue.
1 other instance I use at home with similar setup I also tested and on this one it does work yes without issues.

So what is wrong on those 2 servers?
Both running Ubuntu 18 LTS, Apache 2.4, PHP 7.2.15, mysql 10.1.38
