### ISSUE TITLE
invisible tags not accessible for retention

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/files_retention#59]
### Steps to reproduce
1. Create a new tag under "Collaborative tags" with the attribute "invisible"
2. Open the "select tag" menu under "File retention"

### Expected behaviour
Invisible Tags show up amongst public and restricted tags.

### Actual behaviour
Only public and restricted tags are shown in the list.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**List of activated apps:**

  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.4
  - circles: 0.16.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - deck: 0.5.2
  - end_to_end_encryption: 1.1.0
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_automatedtagging: 1.5.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.3
  - files_fulltextsearch_tesseract: 1.2.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.3
  - fulltextsearch_elasticsearch: 1.2.2
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.2
  - spreed: 5.0.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - terms_of_service: 1.1.1
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_saml: 2.1.0
  - user_sql: 4.3.0
  - workflowengine: 1.5.0

**Comment by michag86** [comment]
I cannot confirm this with Nextcloud 15.0.7 and files_retention 1.4.2
![grafik](https://user-images.githubusercontent.com/6691165/57274378-6055fa80-709b-11e9-9c6d-ca2dcb10fc9b.png)

Can this be closed?

**Comment by KrullBorg** [comment]
i can confirm on nextcloud 17.0.1: it is only visible immediately after the tag creation
