### ISSUE TITLE
Delete folders

### ISSUE THREAD

**Issue by amarttinez** [nextcloud/files_retention#69]
### Steps to reproduce
1. Create a Tag for use with Automated Tagging
2. Setup a Retention rule for that Tag
3. Wait for the rule to be active

### Expected behaviour
All tagged uploads should be deleted

### Actual behaviour
All files are deleted correctly. But, all folders structure keeps empty. If a folder (with multiple sub folders) is uploaded, after FileRetention is executed all the folder and sub folders structure keeps empty.

### Request
Our request is the possibility to delete all tagged uploads, including folders. After a RetentionFile policy match, all files and folders also, should be deleted.

**Comment by sualko** [comment]
Is your feature request to delete folders too? That should already work.

**Comment by AliceOrBob** [comment]
> Is your feature request to delete folders too? That should already work.

I have the same issue as @amarttinez. I created a tagging rule for uploaded files and folders and a retention policy for that tag. The files and folders got tagged properly. After the retention time, all files within the folders got deleted, but the folders themselves remain (empty). 
@sualko can you give an example for a proper configuration for setting up folder deletion, too?
