### ISSUE TITLE
Choose Folder, in which retention should be active

### ISSUE THREAD

**Issue by Maulwurf16** [nextcloud/files_retention#7]
Nextcloud is absolutely perfect for sending relatively huge files to clients. I often do so while using this Thunderbird Addon:

https://addons.mozilla.org/de/thunderbird/addon/owncloud-for-filelink/

Every so shared File is i Folder called "FileLink" on my Cloud. I wish, there would be a way to tell the retention addon to only work in this folder, as I do not want my Documents or Pictures deleted after 30 days.

**Comment by nickvergessen** [comment]
Well basically what you would do is, you tag the folder with a new SystemTag, e.g.  "Temporary" and then you add a retention period for "Temporary"

**Comment by maprambo** [comment]
I just tried that. It only works on tagged files, not files in a tagged folder.
It would be great if it would work recursively on tagged folders though.
Automatic tagging is not a solution for me because the tags stay when I move files out of the folder.

**Comment by mammuth** [comment]
There is workaround via the automated tagging app which can be used unless this feature is implemented inside the retention app. 

I've explained it here:
https://www.maxi-muth.de/3236/allgemeines/auto-delete-files-in-a-directory-after-a-certain-time-in-nextcloud/
(For the people who come to this issue via Google like I did 😊)

**Comment by helmut72** [comment]
All workarounds are bad for normal users, if there is a company wide policy. It would be great if it's possible to exclude/include folders from auto-tagging/retention. Especially the folders from external storages, which begins for all users with the same name.

**Comment by wiswedel** [comment]
@helmut72 As of Nextcloud 15, you can add a negative RegEx rule on the file's/folder's name. Maybe this fits your usecase.

**Comment by helmut72** [comment]
@wiswedel There are now just 2 instances running. One with retention, one with no retention. This is ok because both are 2 different use cases.

But thank you for the hint. I need to look at it to use it in some very special use case.
