### ISSUE TITLE
Avoid folder labeling

### ISSUE THREAD

**Issue by Nomanto** [nextcloud/files_retention#71]
## Avoid folder labeling
Hello, this is a **Feature Request.**

### Steps to reproduce
1. Create a label to use with automatic labeling
2. Configure a retention rule for this tag
3. Wait for the rule to be active

### Expected behaviour
All file types are deleted automatically to prevent the retention of user data, thanks to the « FileRetention » strategy associated with automatic labeling.

### Current behavior
All files are deleted correctly. But, including the structure of the folders that were shared with users. The folder (s) and subfolder (s) containing these files are also tagged. This has the effect of deleting the entire tree set up by the Administrator after executing the FileRetention policy.

### Request

My request is to have the ability to differentiate the labeling of files or folders, to decide whether or not the folder (s) should be taken into account when deleting.
Or,
To have the possibility of preventing the re-issuance of the labeling, once it has been removed by the Administrator.

Thanks a lot,
Nomanto

## Server configuration
**Operating system**:
Linux 4.15.0-44-generic x86_64
**Web server:**
Apache / 2.4.29 (Ubuntu) (apache2handler)
**Database:**
mysql 5.7.26
**PHP version:**
7.3.5-1 + ubuntu18.04.1
**Nextcloud version:**
16.0.1 - 16.0.1.1

### Client configuration
**Navigator:**
Google Chrome / Firefox

**Comment by nickvergessen** [comment]
You can simply add an additional condition to the autotagging:
"`File MIME type` `is not` `httpd/unix-directory`"

Then directories will not be tagged
