### ISSUE TITLE
NC17 compatibility

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/files_retention#74]
Retention 1.5.1 does not seem NC 17 ready. The NC updater is missing an update. I am running NC 16.0.5:

![Bildschirmfoto 2019-09-30 um 10 44 18](https://user-images.githubusercontent.com/43957716/65863770-0cf98700-e371-11e9-9f41-8f4f71423d94.png)

**Comment by nickvergessen** [comment]
Retention 1.6.0 will be 17 compatible. It just needs to be released to the app store

**Comment by rullzer** [comment]
My bad. I'll make sure this gets done today

**Comment by rullzer** [comment]
Done
