### ISSUE TITLE
File retention does not work in Group Folders 

### ISSUE THREAD

**Issue by GnutellaCode** [nextcloud/files_retention#87]
1.Create a public tag
2. Assign a tag to a file in a group folder/group folder
3. wait until the expiration e.g. 1 day

### Expected behaviour
The file in the group folder should be deleted

### Actual behaviour
The file is still there and not deleted

The deletion of files in private folder is operational!

### Server configuration

**Operating system**:
Ubuntu 18.0.4.3 LTS

**Web server:**
Apache2 in version 2.4.29

**Database:**
mysql

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
17.0.3

**Where did you install Nextcloud from:**
from scratch via command line.

**List of activated apps:**
Accessibility
Activity
Auditing/logging
Brute-force settings
Collaborative Tags
Comments
Deleted files
Federation
File sharing
Files automated tagging
First run wizard
Gallery
Group folders
Log Reader
Monitoring
NextCloud announcements
Notifications
Password policy
PDF viewer
Privacy
Recommendations
Retention
Right click
Share by mail
Support
Text
Theming
Two factor TOTP provider
Update notification
Usage survey
Version
Video player

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

When i run the command i get the error "Could not open input file: occ"
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

Same here!
or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

Config php:

<?php
$CONFIG = array (
  'instanceid' => 'oc96xzka5adg',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '192.168.10.50',
    1 => 'files.ebertlang.com',
  ),
  'datadirectory' => '/home/data/',
  'dbtype' => 'mysql',
  'version' => '17.0.3.1',
  'overwrite.cli.url' => 'http://192.168.20.139',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'administrator',
  'datadirectory' => '/home/data/',
  'dbtype' => 'mysql',
  'version' => '17.0.3.1',
  'overwrite.cli.url' => 'http://192.168.20.139',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'administrator',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => '',
  'mail_domain' => '',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'maintenance' => false,
  'mail_smtphost' => '',
  'mail_smtppassword' => '',
  'mail_smtpsecure' => 'tls',
  'theme' => '',
  'loglevel' => 2,
  'simpleSignUpLink.shown' => false,
  'filelocking.enabled' => false,
  'session_lifetime' => 60 * 60 * 1,
  'session_keepalive' => true,
  'updater.release.channel' => 'stable',
  'trashbin_retention_obligation' => 'auto,5',
);

### Client configuration
**Browser:**
Google Chrome, Firefox newest versions
**Operating system:**
Windows 10 1909
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```
The nextcloud log is empty.

Thanks for your help!

**Comment by ChR-iSz** [comment]
Use the full path to occ command, like `sudo -u www-data php /var/www/html/occ app:list`
