### ISSUE TITLE
Notification that file will be deleted is sent every 24 hours even a month before

### ISSUE THREAD

**Issue by jacotec** [nextcloud/files_retention#88]
When you add a retention to a file or folder which is longer than one day and enable the notification that your file will be deleted in 24 hours, you'll get the notification every single day.

### Steps to reproduce
1. Add a file with a retention of 30 days
2. Enable "Notify users a day before retention will delete a file

### Expected behaviour
The user should get a notification one day before retention deletes the file

### Actual behaviour
The user gets a notification *every* day that the file will be deleted in 24 hours (even if it's been deleted in 29 days). 

Nextcloud: 18.0.3
Retention: 1.7.0

**Comment by critot** [comment]
yes, same problem here with a retention of 60 days; users are worried for continuous warnings and call me constantly... please fix it, thank you
Nextcloud: 18.0.3
Retention: 1.7.0

**Comment by mrizvic** [comment]
Same here.
Nextcloud: 18.0.4
Retention: 1.7.0
![image](https://user-images.githubusercontent.com/1878580/82300314-f020cb00-99b6-11ea-901b-b3f87e7e56a5.png)
![image](https://user-images.githubusercontent.com/1878580/82300340-fa42c980-99b6-11ea-84ee-5f1b21b78499.png)

**Comment by mrizvic** [comment]
> Similar here. I removed retention_30days tag and i keep getting notofication even after few days are passed by (see screenshots).
> 
> Nextcloud: 18.0.4
> Retention: 1.7.0
 That is strange, file had retention tag even after it was removed:
```
(nextcloud_db)root# SELECT * FROM oc_systemtag_object_mapping WHERE objectid='2569';
+----------+------------+-------------+
| objectid | objecttype | systemtagid |
+----------+------------+-------------+
| 2569     | files      |           2 |
+----------+------------+-------------+
1 row in set (0.001 sec)

```
I shared the "Mail-attachments" folder with admin who removed the system/invisible tag and then SELECT query returned with 0 rows.

**Comment by cClaude** [comment]
It's seen that this merge request fixed that issue: https://github.com/nextcloud/files_retention/pull/92
@jacotec  If I'm right, could you close this issues, to remove noise ?

**Comment by sualko** [comment]
Since the pr is fixing the issue, I close this.

> That is strange, folder had retention tag even after it was removed

This app is not removing the tag, because it should not be needed.
