### ISSUE TITLE
Nextcloud 19 compatibility

### ISSUE THREAD

**Issue by ntimo** [nextcloud/files_retention#91]
### Steps to reproduce
1. Update to Nextcloud 19
2. Go to Settings --> Apps
3. The app is deactivated because it does not Support Nextcloud 19

### Expected behaviour
The app should support Nextcloud 19

### Actual behaviour
It only supports Nextcloud 18

### Server configuration
**Nextcloud version:** 19.0.0

**Where did you install Nextcloud from:**
self build nextcloud 19 docker image

**Comment by ginkeltjes** [comment]
Same problem here, any idea when we can expect an update for NC19 support ?

**Comment by blizzz** [comment]
a 19 compatible release was published on Jun 12

**Comment by ginkeltjes** [comment]
Ive updated the but its not showing the retention module for the settings. So somehow its not working completely?

**Comment by blizzz** [comment]
Cannot reproduce

![Screenshot_20200810_115451](https://user-images.githubusercontent.com/2184312/89771267-56257600-db00-11ea-92c7-af700f1be17e.png)

**Comment by ginkeltjes** [comment]
Uh, User Retention? I think thats something else.

**Comment by blizzz** [comment]
> Uh, User Retention? I think thats something else.

too many context switches :zany_face: 

What about:

![Screenshot_20200810_145058](https://user-images.githubusercontent.com/2184312/89784438-f5566780-db18-11ea-89b6-15537a6d8c09.png)

**Comment by ginkeltjes** [comment]
Ah yeah, there it is! Has this been moved? It wasn't there before right?

**Comment by blizzz** [comment]
> Ah yeah, there it is! Has this been moved? It wasn't there before right?

Nah, it was not moved, but the we had fundamental changes around Flow towards 18. Now, this app does not fit in this section anymore, and should be brought somewhere else.
