### ISSUE TITLE
files_retention deletes marked file in shared folders including the shared folder

### ISSUE THREAD

**Issue by sloesp** [nextcloud/files_retention#98]
Hello,

our enviroment consists of shared folders in which we are putting files for our customers. File_retention should supervise these files and delete them by reaching the age for delete. But after reaching the delete age the file and the folder in which the file was were deleted. Not only the file as expected.

This behavior was tested with nextcloud 19.0.3 and files_retention 1.8.2

Can anybody help me to keep the shared folders.

Thanks so far.

      

### Steps to reproduce
1. Create for User A a folder and share it to a member group G
2. User B which is in member Group G is putting a file in the shared folder for User A. The file is automaticly marked for file retention after two days 
3. After two days the file and the shared folder is delete

### Expected behaviour
After two days only the file should be deleted.

### Actual behaviour
After two days the file and the shared folder is delete

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version: 7.4

**Nextcloud version: 19.0.3

**Where did you install Nextcloud from:**

**List of activated apps:**

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.1
  - files_automatedtagging: 1.9.0
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.0.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflow_script: 1.4.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - files_external
  - sharebymail
  - user_ldap

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "stbslocloud.ddnss.de",
            "172.30.20.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwrite.cli.url": "https:\/\/stbslocloud.ddnss.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "default_locale": "de_DE",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "465",
        "trashbin_retention_obligation": "auto,1",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}



### Client configuration
**Browser:**

**Operating system:**

### Logs

#### Nextcloud log (data/owncloud.log)
nothing with the item files_retention in this file

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by sualko** [comment]
Hi @sloesp, quite some time past, but do you still have this issue? Can you verify that the shared folder is not having the retention tag you configured? I looked at the code and I see nothing which could trigger your described behaviour.
